# nee: laptop display with an optional headless output.
output * bg /share/Pictures/wallpapers/current fill

output eDP-1 {
  position 0 0
}

output HEADLESS-1 {
  resolution 1920x1200 position 1920 0
  bg "#220900" solid_color
  disable
}
